[package]
name = "arpack-ng"
version = "0.1.0"
authors = ["Daniel Hauck <mail@dhauck.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arpack-ng-sys = { path = "../arpack-ng-sys" }
num-complex = "0.2"
ndarray = "0.13.0"
num-traits = "0.2.9"
blas-src = { version = "0.4", features = ["openblas"] }
lapack-src = { version = "0.4", features = ["openblas"] }
openblas-src = { version = "0.7", features = ["system", "cblas"] }
